# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "20 03 * * *"
    displayName: "Daily Build"
    branches:
      include: ["dev"]
    always: "false" # Don't run unless changes happen


pool:
  vmImage: 'windows-2019'

steps:

#- task: PythonScript@0
#  displayName: Generate Core Projects
#  inputs:
#    scriptSource: 'filePath'
#    scriptPath: 'src/devtools/pyqpc/PyQPC.py'
#    arguments: '/basefile "../../vpc_scripts/default.vgc" +libraries /vs2019 /mksln core'
#    # change back to +core later when i try getting shaders to build here

# no difference from MSBuild@1?
#- task: VSBuild@1
#  displayName: Build the core projects
#  inputs:
#    solution: 'src\core.sln'
#    platform: 'win32'
#    configuration: 'Release'
#    maximumCpuCount: true

- task: PythonScript@0
  displayName: Generate Engine Dependencies
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/pyqpc/PyQPC.py'
    # oof
    arguments: '/basefile "../../vpc_scripts/default.vgc" +tier0 +tier1 +tier2 +tier3 +vstdlib +appframework +mathlib +matsys_controls +jpeglib +shaderlib +bitmap +bzip2 +choreoobjects +dmxloader +particles +vtf +vgui_controls +vgui_surfacelib /vs2019 /mksln deps'
    
# no difference from MSBuild@1?
- task: VSBuild@1
  displayName: Build Engine Dependencies
  inputs:
    solution: 'src\deps.sln'
    platform: 'win32'
    configuration: 'Release'
    maximumCpuCount: true

- task: PythonScript@0
  displayName: Generate Engine Projects
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/pyqpc/PyQPC.py'
    arguments: '/basefile "../../vpc_scripts/default.vgc" /episodic +game -libraries -stdshader_dbg -stdshader_dx9 -filesystem_steam -gameui_client /vs2019 /mksln engine'
    
# no difference from MSBuild@1?
- task: VSBuild@1
  displayName: Build the Engine projects
  inputs:
    solution: 'src\engine.sln'
    platform: 'win32'
    configuration: 'Release'
    maximumCpuCount: true

# idk if i need to compress it
- task: ArchiveFiles@2
  displayName: Compress game folder with 7z
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/game'
    includeRootFolder: true
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/QuiverSource_$(Build.BuildId).7z'
    replaceExistingArchive: true

- task: GitHubRelease@0
  displayName: Release to github
  inputs:
    gitHubConnection: 'github test'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: '$(Build.BuildNumber)'
    title: 'Auto Build - $(Build.BuildNumber)'
    assets: '$(Build.ArtifactStagingDirectory)/QuiverSource_$(Build.BuildId).7z'
    isDraft: true
