# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "20 03 * * *"
    displayName: "Daily Build"
    branches:
      include: ["dev"]
    always: "false" # Don't run unless changes happen


pool:
  vmImage: 'windows-2019'

steps:
- task: PythonScript@0
  displayName: Generate Engine and Util Projects
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/pyqpc/PyQPC.py'
    # arguments: '/basefile "../../vpc_scripts/default.vgc" /episodic +game -libraries -stdshader_dbg -stdshader_dx9 -filesystem_steam -gameui_client /vs2019 /mksln engine'
    arguments: '/basefile "../../vpc_scripts/default.vgc" /episodic +game +vmpi +raytrace +fgdlib +utils -gameui_client -bsppack -ep2_deathmap -vtex_dll -vtex_launcher -normal2ssbump -height2normal -height2ssbump -hammer_dll -hammer_launcher -stdshader_dbg -stdshader_dx9 /vs2019 /mksln engine'
    
# no difference from MSBuild@1?
- task: VSBuild@1
  displayName: Build the Engine and Utils
  inputs:
    solution: 'src\engine.sln'
    platform: 'win32'
    configuration: 'Release'
    maximumCpuCount: true

# idk if i need to compress it
- task: ArchiveFiles@2
  displayName: Compress game folder with 7z
  inputs:
    rootFolderOrFile: 'game/'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: 'QuiverSource_$(Build.BuildId).7z'
    replaceExistingArchive: true

# maybe add more assets for source code and shaders?
- task: GitHubRelease@0
  displayName: Release to github
  inputs:
    gitHubConnection: 'github test'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: '$(Build.BuildNumber)'
    title: 'Auto Build $(Build.BuildId) - $(Build.BuildNumber)'
    assets: 'QuiverSource_$(Build.BuildId).7z'
    isDraft: true
