# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "20 03 * * *"
    displayName: "Daily Build"
    branches:
      include: ["dev"]
    always: "false" # Don't run unless changes happen


pool:
  vmImage: 'windows-2019'

steps:

# Generate the projects
- task: CmdLine@2
  displayName: Generate Projects
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src\
      
      devtools\bin\vpc.exe /allgames +game -stdshader_dbg -stdshader_dx9 /define:VS2019 /mksln engine.sln
    '

# Build Core Projects
- task: MSBuild@1
  displayName: Build Projects
  inputs:
    solution: "src/core.sln" #"**/*.sln"
    configuration: "Release"
