# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "20 03 * * *"
    displayName: "Daily Build"
    branches:
      include: ["dev"]
    always: "false" # Don't run unless changes happen


pool:
  vmImage: 'windows-2019'

steps:

- task: CmdLine@2
  displayName: Generate Core Projects
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src/

      devtools\bin\vpc.exe +core /define:VS2019 /mksln core.sln
    '
    
- task: DevEnvBuild@2
  displayName: Build the core projects
  inputs:
    solution: 'src\core.sln'
    buildCfg: 'Release'
    vsVersion: 'latest'
    clean: true

- task: CmdLine@2
  displayName: Build All Shaders
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src/materialsystem/stdshaders/

      call _buildallshaders.bat
    '

- task: CmdLine@2
  displayName: Generate Engine Projects
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src/
      
      devtools\bin\vpc.exe /allgames +game /define:VS2019 /mksln engine.sln
    '

- task: DevEnvBuild@2
  displayName: Build the engine
  inputs:
    solution: 'src\engine.sln'
    buildCfg: 'Release'
    vsVersion: 'latest'
    clean: true
    # i really don't want to use "clean: true", but otherwise it just kills itself if i don't


