pool:
  vmImage: 'windows-2019'


steps:
- task: PythonScript@0
  displayName: Generate Lib Projects
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/pyqpc/PyQPC.py'
    arguments: '/basefile "../../vpc_scripts/default_qpc.vgc" +libraries /vs2019 /mksln libraries_x64'
    
- task: PythonScript@0
  displayName: Generate Bin Projects
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/pyqpc/PyQPC.py'
    arguments: '/basefile "../../vpc_scripts/default_qpc.vgc" +binaries /vs2019 /mksln binaries_x64'
          
- task: PythonScript@0
  displayName: Auto Generate Issue 50
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/auto_issue50.py'
    arguments: '$(git_token)'