# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "20 03 * * *"
    displayName: "Daily Build"
    branches:
      include: ["dev"]
    always: "false" # Don't run unless changes happen


pool:
  vmImage: 'windows-2019'

steps:

# Generate the projects
- task: CmdLine@2
  displayName: Generate Projects
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src\
      
      devtools\bin\vpc.exe /hl2 /hl2mp /episodic /hl2r +game +utils +tools -bsppack -bzip2 -ep2_deathmap -vtex_dll -vtex_launcher -normal2ssbump -height2normal -height2ssbump /define:VS2019 /mksln engine_and_tools.sln
    '

# Run VPC Batch Script
- task: BatchScript@1
  inputs:
    filename: 'src/_create_coreprojects.bat'

# Build Core Projects
- task: MSBuild@1
  displayName: Build Projects
  inputs:
    solution: "src/core.sln" #"**/*.sln"
    configuration: "Release"
