# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "20 03 * * *"
    displayName: "Daily Build"
    branches:
      include: ["dev"]
    always: "false" # Don't run unless changes happen


pool:
  vmImage: 'windows-2019'

steps:

- task: PythonScript@0
  displayName: Generate Core Projects
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/pyqpc/PyQPC.py'
    arguments: '/basefile "../../vpc_scripts/default.vgc" +core /vs2019 /mksln core'

- task: DevEnvBuild@2
  displayName: Build the core projects
  inputs:
    solution: 'src\core.sln'
    buildCfg: 'Release'
    vsVersion: 'latest'

- task: CmdLine@2
  displayName: Build All Shaders
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src/materialsystem/stdshaders/

      call _buildallshaders.bat
    '

- task: PythonScript@0
  displayName: Generate Engine Projects
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/pyqpc/PyQPC.py'
    arguments: '/basefile "../../vpc_scripts/default.vgc" /hl2 /hl2mp /episodic +game -core /vs2019 /mksln engine'
    
- task: DevEnvBuild@2
  displayName: Build the engine
  inputs:
    solution: 'src\engine.sln'
    buildCfg: 'Release'
    vsVersion: 'latest'


