pool:
  vmImage: 'windows-2019'


# useful variables:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml


steps:
- task: BatchScript@1
  displayName: Generate Projects
  inputs:
    filename: 'src/_create_allprojects.bat'

- task: PythonScript@0
  displayName: Build and Check for Issue 50
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/auto_issue50.py'
    workingDirectory: 'src/'
    arguments: '$(git_token)'
