# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "20 03 * * *"
    displayName: "Daily Build"
    branches:
      include: ["dev"]
    always: "false" # Don't run unless changes happen


pool:
  vmImage: 'windows-2019'

steps:

- task: CmdLine@2
  displayName: Generate Core Projects
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src/

      devtools\bin\vpc_patched.exe +core /define:VS2019 /mksln core.sln
    '

- task: PythonScript@0
  displayName: Running a dirty hack to fix the fucked sln file from patched VPC
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/vpc_fucking_sucks.py'
    arguments: '-sln "%cd%\src\core.sln"'

- task: DevEnvBuild@2
  displayName: Build the core projects
  inputs:
    solution: 'src\core_fixed.sln'
    buildCfg: 'Release'
    vsVersion: 'latest'
    clean: true

- task: CmdLine@2
  displayName: Build All Shaders
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src/materialsystem/stdshaders/

      call _buildallshaders.bat
    '

- task: CmdLine@2
  displayName: Generate Engine Projects
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)"
    script: '
      cd src/
      
      devtools\bin\vpc_patched.exe /allgames +game /define:VS2019 /mksln engine.sln
    '

- task: PythonScript@0
  displayName: Running a dirty hack to fix the fucked sln file from patched VPC
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/devtools/vpc_fucking_sucks.py'
    arguments: '-sln "%cd%\src\engine.sln"'

- task: DevEnvBuild@2
  displayName: Build the engine
  inputs:
    solution: 'src\engine_fixed.sln'
    buildCfg: 'Release'
    vsVersion: 'latest'
    clean: true


